#!/usr/bin/env bash
#
# Writes a .env with random free ports, a random database name and user, and
# freshly generated secrets. Run once per deployment.
#
#   ./scripts/gen-env.sh
#
# Refuses to clobber an existing .env. Delete it first if you really mean it.

set -euo pipefail

cd "$(dirname "$0")/.."

if [ -e .env ]; then
    echo "refusing to overwrite the existing .env, move it out of the way first" >&2
    exit 1
fi

need() {
    command -v "$1" >/dev/null 2>&1 || { echo "missing required command: $1" >&2; exit 1; }
}
need openssl

# Is this port free on the host right now?
port_free() {
    local p=$1
    if command -v ss >/dev/null 2>&1; then
        ! ss -HltnO "sport = :$p" 2>/dev/null | grep -q .
    elif command -v lsof >/dev/null 2>&1; then
        ! lsof -iTCP:"$p" -sTCP:LISTEN -n -P >/dev/null 2>&1
    else
        # No way to check, so just take it and hope.
        return 0
    fi
}

# Pick from the dynamic range, above anything that hands out ephemeral ports by default.
random_port() {
    local p
    for _ in $(seq 1 60); do
        p=$(( 20000 + RANDOM % 40000 ))
        if port_free "$p"; then
            echo "$p"
            return 0
        fi
    done
    echo "could not find a free port after 60 tries" >&2
    exit 1
}

APP_PORT=$(random_port)
APP_INTERNAL_PORT=$(random_port)
DB_PORT=$(random_port)

# Alphanumeric only. Postgres identifiers and connection strings both get unhappy
# otherwise, and the url is built by string concatenation in compose.
# Hex rather than /dev/urandom piped into head, because head closing the pipe
# early kills tr with SIGPIPE and set -o pipefail turns that into a hard exit.
rand_alnum() {
    openssl rand -hex "$1" | cut -c "1-$1"
}

POSTGRES_USER="u_$(rand_alnum 12)"
POSTGRES_DB="d_$(rand_alnum 12)"
POSTGRES_PASSWORD="$(rand_alnum 40)"
SESSION_SECRET="$(openssl rand -hex 32)"
AUTH_PASSWORD="$(rand_alnum 20)"

cat > .env <<EOF
# generated by scripts/gen-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# every value here is random. do not commit this file.

# ==== ports ====

# Host side. This is what nginx proxies to.
APP_BIND=127.0.0.1
APP_PORT=${APP_PORT}

# Inside the container. Namespaced, so it only has to not collide with itself,
# but it is random anyway.
APP_INTERNAL_PORT=${APP_INTERNAL_PORT}

# Only used if you uncomment the db ports block in docker-compose.yml.
DB_BIND=127.0.0.1
DB_PORT=${DB_PORT}

# ==== database ====

POSTGRES_VERSION=16-alpine
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Only needed when running outside compose. Compose builds this itself.
# DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${DB_PORT}/${POSTGRES_DB}?sslmode=disable

# ==== auth ====

# The one shared password. This is what you and the other person type.
AUTH_PASSWORD=${AUTH_PASSWORD}

# Signs the session cookie.
SESSION_SECRET=${SESSION_SECRET}

# ==== features ====

# Stem separation. On. Adds about two gigabytes to the image because of torch.
WITH_DEMUCS=1
DEMUCS_BIN=demucs
DEMUCS_MODEL=htdemucs

# ==== misc ====

DATA_DIR=/data
MAX_UPLOAD_MB=300
SECURE_COOKIE=true
YTDLP_BIN=yt-dlp
FFMPEG_BIN=ffmpeg
FFPROBE_BIN=ffprobe
EOF

chmod 600 .env

echo "wrote .env"
echo
echo "  app on host      127.0.0.1:${APP_PORT}   <- point nginx here"
echo "  app in container :${APP_INTERNAL_PORT}"
echo "  db port (unused unless published) ${DB_PORT}"
echo
echo "  sign in password: ${AUTH_PASSWORD}"
echo
echo "next: docker compose up -d --build"
